### ISSUE TITLE
Custom scales show TWh lower than MWh

### ISSUE THREAD

**Issue by gilesdring** [odileeds/ukpn-heat-street#3] opened 2021-06-29 13:17 UTC
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1731108/123803948-a78b4f00-d8e4-11eb-83ff-a02f700e1e9d.png">

**Comment by gilesdring** [comment] 2021-06-29 13:40
<img width="335" alt="image" src="https://user-images.githubusercontent.com/1731108/123807665-f7b7e080-d8e7-11eb-8f92-33e933491eb5.png">

**Comment by slowe** [comment] 2021-07-01 17:27
A duplicate of issue #9

**Closed as completed by slowe** 2021-07-01 17:27 UTC
